"""users, alert audit, message alert link, checkin household index

Revision ID: d0efb4a80898
Revises: fa119c9c13d9
Create Date: 2026-10-04 03:42:09.150381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0efb4a80898'
down_revision: Union[str, None] = 'fa119c9c13d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATOR', 'RESPONDER', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.add_column('alerts', sa.Column('issued_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'alerts', 'users', ['issued_by_id'], ['id'])
    op.add_column('checkins', sa.Column('assigned_to_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_checkins_household_id'), 'checkins', ['household_id'], unique=False)
    op.create_foreign_key(None, 'checkins', 'users', ['assigned_to_id'], ['id'])
    op.drop_column('checkins', 'assigned_to')
    op.add_column('messages', sa.Column('alert_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_messages_alert_id'), 'messages', ['alert_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'alerts', ['alert_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_alert_id'), table_name='messages')
    op.drop_column('messages', 'alert_id')
    op.add_column('checkins', sa.Column('assigned_to', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'checkins', type_='foreignkey')
    op.drop_index(op.f('ix_checkins_household_id'), table_name='checkins')
    op.drop_column('checkins', 'assigned_to_id')
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_column('alerts', 'issued_by_id')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
