"""household and message channel

Revision ID: dca2324282db
Revises: d0efb4a80898
Create Date: 2026-10-04 05:22:57.940963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dca2324282db'
down_revision: Union[str, None] = 'd0efb4a80898'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('SMS', 'WHATSAPP', name='channel').create(op.get_bind(), checkfirst=True)
    op.add_column('households', sa.Column('channel', sa.Enum('SMS', 'WHATSAPP', name='channel'), server_default='SMS', nullable=False))
    op.add_column('messages', sa.Column('channel', sa.Enum('SMS', 'WHATSAPP', name='channel'), server_default='SMS', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'channel')
    op.drop_column('households', 'channel')
    sa.Enum(name='channel').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
