"""initial schema

Revision ID: fa119c9c13d9
Revises: 
Create Date: 2026-10-04 00:21:45.991367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = 'fa119c9c13d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('households',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('head_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('members', sa.Integer(), nullable=False),
    sa.Column('vulnerable', sa.Integer(), nullable=False),
    sa.Column('geom', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('consent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_geospatial_index('ix_households_geom', 'households', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_households_id'), 'households', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_msg_id', sa.String(), nullable=True),
    sa.Column('direction', sa.Enum('INBOUND', 'OUTBOUND', name='message_direction'), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_msg_id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_phone'), 'messages', ['phone'], unique=False)
    op.create_geospatial_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('risk_level', sa.Integer(), nullable=False),
    sa.Column('geom', Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('ix_zones_geom', 'zones', ['geom'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_zones_id'), 'zones', ['id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Enum('WARNING', 'EVACUATE', name='severity'), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'WEATHER', 'SIMULATION', name='alert_source'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_table('checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('SENT', 'RESENT', 'CALLING', 'UNREACHABLE', 'NEEDS_HELP', 'ASSIGNED', 'SAFE', 'RESCUED', 'CLOSED', name='checkin_state'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('next_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_id', 'household_id', name='uq_checkins_alert_household')
    )
    op.create_index('ix_checkins_due', 'checkins', ['next_action_at'], unique=False, postgresql_where=sa.text("state NOT IN ('SAFE', 'RESCUED', 'CLOSED')"))
    op.create_index(op.f('ix_checkins_id'), 'checkins', ['id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('checkin_id', sa.Integer(), nullable=False),
    sa.Column('from_state', sa.Enum('SENT', 'RESENT', 'CALLING', 'UNREACHABLE', 'NEEDS_HELP', 'ASSIGNED', 'SAFE', 'RESCUED', 'CLOSED', name='checkin_state'), nullable=True),
    sa.Column('to_state', sa.Enum('SENT', 'RESENT', 'CALLING', 'UNREACHABLE', 'NEEDS_HELP', 'ASSIGNED', 'SAFE', 'RESCUED', 'CLOSED', name='checkin_state'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['checkin_id'], ['checkins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_checkin_id'), 'events', ['checkin_id'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_checkin_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_checkins_id'), table_name='checkins')
    op.drop_index('ix_checkins_due', table_name='checkins', postgresql_where=sa.text("state NOT IN ('SAFE', 'RESCUED', 'CLOSED')"))
    op.drop_table('checkins')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_zones_id'), table_name='zones')
    op.drop_geospatial_index('ix_zones_geom', table_name='zones', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('zones')
    op.drop_index(op.f('ix_messages_phone'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_households_id'), table_name='households')
    op.drop_geospatial_index('ix_households_geom', table_name='households', postgresql_using='gist', column_name='geom')
    op.drop_geospatial_table('households')
    # ### end Alembic commands ###
    for enum_name in ("message_direction", "checkin_state", "alert_source", "severity"):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)